const DEFAULT_CIVITAI_API_BASE_URL = "https://civitai.com";
const DEFAULT_CIVITAI_WEB_BASE_URL = "https://civitai.com";
const DEFAULT_CIVITAI_MODELS_PATH = "/api/v1/models";
const DEFAULT_CIVITAI_MODEL_TYPE = "LORA";
const DEFAULT_CIVITAI_REQUEST_TIMEOUT_MS = 15000;
const DEFAULT_CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT = 20;
const DEFAULT_CIVITAI_BASEMODEL_SCAN_PAGE_SIZE = 100;
const DEFAULT_CIVITAI_ORCHESTRATION_BASE_URL =
  "https://orchestration.civitai.com";
const DEFAULT_CIVITAI_ORCHESTRATION_JOBS_PATH = "/v1/consumer/jobs";
const MIN_CIVITAI_REQUEST_TIMEOUT_MS = 1000;
const MAX_CIVITAI_REQUEST_TIMEOUT_MS = 120000;
const MIN_CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT = 1;
const MAX_CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT = 100;
const MIN_CIVITAI_BASEMODEL_SCAN_PAGE_SIZE = 20;
const MAX_CIVITAI_BASEMODEL_SCAN_PAGE_SIZE = 100;

const DEFAULT_LORA_SYNC_LIMIT = 20;
const DEFAULT_LORA_SYNC_MAX_LIMIT = 80;
const MIN_LORA_SYNC_LIMIT = 1;
const MAX_LORA_SYNC_LIMIT = 200;

const DEFAULT_LORA_PROFILE_MAX_ITEMS_PER_MODALITY = 6;
const MIN_LORA_PROFILE_ITEMS = 1;
const MAX_LORA_PROFILE_ITEMS = 24;

const DEFAULT_LORA_STRENGTH = 1;
const MIN_LORA_STRENGTH = 0;
const MAX_LORA_STRENGTH = 2;

const DEFAULT_CHARACTER_PROFILE_SEARCH_LIMIT = 100;

const LORA_CATALOG_TYPE = "LORACAT";
const LORA_PROFILE_TYPE = "LORAPROFILE";

const LORA_MODALITY_IMAGE = "image";
const LORA_MODALITY_VIDEO = "video";
const LORA_MODALITIES = Object.freeze([
  LORA_MODALITY_IMAGE,
  LORA_MODALITY_VIDEO,
]);

const parseIntegerEnv = (
  value,
  fallback,
  min = Number.MIN_SAFE_INTEGER,
  max = Number.MAX_SAFE_INTEGER
) => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(Math.max(Math.round(parsed), min), max);
};

const parseNumberEnv = (
  value,
  fallback,
  min = Number.MIN_SAFE_INTEGER,
  max = Number.MAX_SAFE_INTEGER
) => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(Math.max(parsed, min), max);
};

const LORA_SYNC_DEFAULT_LIMIT = parseIntegerEnv(
  process.env.LORA_SYNC_DEFAULT_LIMIT,
  DEFAULT_LORA_SYNC_LIMIT,
  MIN_LORA_SYNC_LIMIT,
  MAX_LORA_SYNC_LIMIT
);
const LORA_SYNC_MAX_LIMIT = parseIntegerEnv(
  process.env.LORA_SYNC_MAX_LIMIT,
  DEFAULT_LORA_SYNC_MAX_LIMIT,
  MIN_LORA_SYNC_LIMIT,
  MAX_LORA_SYNC_LIMIT
);
const LORA_PROFILE_MAX_ITEMS_PER_MODALITY = parseIntegerEnv(
  process.env.LORA_PROFILE_MAX_ITEMS_PER_MODALITY,
  DEFAULT_LORA_PROFILE_MAX_ITEMS_PER_MODALITY,
  MIN_LORA_PROFILE_ITEMS,
  MAX_LORA_PROFILE_ITEMS
);
const LORA_STRENGTH_DEFAULT = parseNumberEnv(
  process.env.LORA_STRENGTH_DEFAULT,
  DEFAULT_LORA_STRENGTH,
  MIN_LORA_STRENGTH,
  MAX_LORA_STRENGTH
);

const CIVITAI_API_BASE_URL =
  process.env.CIVITAI_API_BASE_URL || DEFAULT_CIVITAI_API_BASE_URL;
const CIVITAI_WEB_BASE_URL =
  process.env.CIVITAI_WEB_BASE_URL || DEFAULT_CIVITAI_WEB_BASE_URL;
const CIVITAI_MODELS_PATH =
  process.env.CIVITAI_MODELS_PATH || DEFAULT_CIVITAI_MODELS_PATH;
const CIVITAI_MODEL_TYPE = DEFAULT_CIVITAI_MODEL_TYPE;
const CIVITAI_ORCHESTRATION_BASE_URL =
  process.env.CIVITAI_ORCHESTRATION_BASE_URL ||
  DEFAULT_CIVITAI_ORCHESTRATION_BASE_URL;
const CIVITAI_ORCHESTRATION_JOBS_PATH =
  process.env.CIVITAI_ORCHESTRATION_JOBS_PATH ||
  DEFAULT_CIVITAI_ORCHESTRATION_JOBS_PATH;
const CIVITAI_REQUEST_TIMEOUT_MS = parseIntegerEnv(
  process.env.CIVITAI_REQUEST_TIMEOUT_MS,
  DEFAULT_CIVITAI_REQUEST_TIMEOUT_MS,
  MIN_CIVITAI_REQUEST_TIMEOUT_MS,
  MAX_CIVITAI_REQUEST_TIMEOUT_MS
);
const CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT = parseIntegerEnv(
  process.env.CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT,
  DEFAULT_CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT,
  MIN_CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT,
  MAX_CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT
);
const CIVITAI_BASEMODEL_SCAN_PAGE_SIZE = parseIntegerEnv(
  process.env.CIVITAI_BASEMODEL_SCAN_PAGE_SIZE,
  DEFAULT_CIVITAI_BASEMODEL_SCAN_PAGE_SIZE,
  MIN_CIVITAI_BASEMODEL_SCAN_PAGE_SIZE,
  MAX_CIVITAI_BASEMODEL_SCAN_PAGE_SIZE
);

module.exports = {
  DEFAULT_CHARACTER_PROFILE_SEARCH_LIMIT,
  LORA_CATALOG_TYPE,
  LORA_PROFILE_TYPE,
  LORA_MODALITY_IMAGE,
  LORA_MODALITY_VIDEO,
  LORA_MODALITIES,
  LORA_SYNC_DEFAULT_LIMIT,
  LORA_SYNC_MAX_LIMIT,
  LORA_PROFILE_MAX_ITEMS_PER_MODALITY,
  LORA_STRENGTH_DEFAULT,
  MIN_LORA_STRENGTH,
  MAX_LORA_STRENGTH,
  CIVITAI_API_BASE_URL,
  CIVITAI_WEB_BASE_URL,
  CIVITAI_MODELS_PATH,
  CIVITAI_MODEL_TYPE,
  CIVITAI_ORCHESTRATION_BASE_URL,
  CIVITAI_ORCHESTRATION_JOBS_PATH,
  CIVITAI_REQUEST_TIMEOUT_MS,
  CIVITAI_BASEMODEL_SCAN_PAGE_LIMIT,
  CIVITAI_BASEMODEL_SCAN_PAGE_SIZE,
};
