const registerCorePromptRoutes = require("./core-prompt");
const registerUserMediaRoutes = require("./media/user-media-routes");
const registerUserVideoRoutes = require("./media/user-video-routes");
const registerSharedMediaRoutes = require("./media/shared-media-routes");
const registerBedrockRoutes = require("./bedrock-routes");
const registerReplicateImageRoutes = require("./replicate-image-routes");
const registerCivitaiImageRoutes = require("./civitai-image-routes");
const registerGradioRoutes = require("./gradio-routes");
const registerReplicateImageStatusSelectRoutes = require("./replicate-image-status-select-routes");
const registerReplicateVideoRoutes = require("./replicate-video-routes");
const registerBedrockImageVideoRoute = require("./bedrock-image-video-route");
const registerStorySeedRoutes = require("./story/seed-routes");
const registerStorySessionRoutes = require("./story/session-routes");
const registerStorySessionItemRoutes = require("./story/session-item-routes");
const registerStoryMessageRoute = require("./story-message-route");
const registerStoryIllustrationRoutes = require("./story/illustration-routes");
const registerStoryAnimationRoutes = require("./story/animation-routes");
const registerStoryMusicRoutes = require("./story/music-routes");
const registerStoryMusicLibraryRoutes = require("./story/music-library-routes");
const registerStoryMusicSelectionRoutes = require("./story/music-selection-routes");
const registerOperationsRoutes = require("./operations-routes");
const registerLoraCatalogRoutes = require("./lora/catalog-routes");
const registerLoraProfileRoutes = require("./lora/profile-routes");
const registerCharacterRoutes = require("./character-routes");
const registerCompanionRoute = require("./companion-route");
const registerAgentRoute = require("./agent-route");
const registerAgentSuggestRoute = require("./agent-suggest-route");
const registerAgentAdminRoute = require("./agent-admin-route");
const registerAgentSessionsRoute = require("./agent-sessions-route");

const registerRoutes = (app, deps) => {
  registerCorePromptRoutes(app, deps);
  app.use("/", registerUserMediaRoutes(deps));
  app.use("/", registerUserVideoRoutes(deps));
  app.use("/", registerSharedMediaRoutes(deps));
  registerBedrockRoutes(app, deps);
  registerReplicateImageRoutes(app, deps);
  registerCivitaiImageRoutes(app, deps);
  registerGradioRoutes(app, deps);
  registerReplicateImageStatusSelectRoutes(app, deps);
  registerReplicateVideoRoutes(app, deps);
  registerBedrockImageVideoRoute(app, deps);
  app.use("/story", registerStorySeedRoutes(deps));
  app.use("/story", registerStorySessionRoutes(deps));
  app.use("/story", registerStorySessionItemRoutes(deps));
  registerStoryMessageRoute(app, deps);
  app.use("/story", registerStoryIllustrationRoutes(deps));
  app.use("/story", registerStoryAnimationRoutes(deps));
  app.use("/story", registerStoryMusicRoutes(deps));
  app.use("/story", registerStoryMusicLibraryRoutes(deps));
  app.use("/story", registerStoryMusicSelectionRoutes(deps));
  registerOperationsRoutes(app, deps);
  app.use("/", registerLoraCatalogRoutes(deps));
  app.use("/", registerLoraProfileRoutes(deps));
  registerCharacterRoutes(app, deps);
  registerCompanionRoute(app, deps);
  registerAgentRoute(app, deps);
  registerAgentSuggestRoute(app, deps);
  registerAgentAdminRoute(app, deps);
  registerAgentSessionsRoute(app, deps);
};

module.exports = {
  registerRoutes,
};
